[package]
name = "aero_test"
version = "0.1.0"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.82", features = ["proc-macro", "full"] }
quote = "1.0.10"
